---
- name: install MongoDB
  hosts: zitel
  become: true
  tasks:
  - name: Import MongoDB public GPG Key
    apt_key:
        keyserver: keyserver.ubuntu.com
        id: 160D26BB1785BA38
  - name: Add MongoDB repository into sources list
    apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/7.0 multiverse
        state: present
  - name: Install MongoDB package
    apt:
        name: mongodb-org
        # update_cache: yes
  - name: start mongodb service
    systemd_service:
      state: started
      daemon_reload: true
      name: mongod