---
- name: install nginx
  hosts: zitel
  become: true
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: latest
    - name: Copy nginx config file
      copy:
        src: "{{ playbook_dir }}/../static-files/default.conf"
        dest: /etc/nginx/conf.d/default.conf
    - name: Reload nginx
      systemd_service:
        state: reloaded
        daemon_reload: true
        name: nginx